### 3-dimensional dot product in numpy

Can we compute dot product of 3-dimensional matrices in numpy? Is it same way as we do for 2D matrices? This was a need when trying to implement convolution neural networks of cs231n course. Let's take a look

In [45]:
import numpy as np

Let's have 2 `3x3` matrices and try to find their dot product. We initialise the matrices with 1's as the we already know what is the dot product of it. Yes it's 27.0

In [46]:
a = np.ones([3,3,3])
b = np.ones([3,3,3])

In [47]:
#compute the dot product.
c = np.dot(a,b)
print(c)

[[[[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]]


 [[[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]]


 [[[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]

  [[ 3.  3.  3.]
   [ 3.  3.  3.]
   [ 3.  3.  3.]]]]


What the hell! We didn't get a dot product as 27.0 but we got whole bunch of `3x3` matrices. Actually numpy's dot works differently than we expect it to work. It's doing matrix multiplication on last axis. Hence this absurd results are infront of us. Is there a simple way to do it in numpy? 

#### Smashing dimensions
Why don't we just smash the dimensions of the matrix find the dot product as numpy does the dot product as expected for the single dimension matrices. So what we have got is function called `ravel` which can give us a single dimensional view of the multidimensional matrix.

In [48]:
# smash the dimensions
ra = a.ravel()
rb = b.ravel()

#now compute the dot product
c = np.dot(ra, rb)

print(c)

27.0
